### ISSUE TITLE
remove layer from admin interface

### ISSUE THREAD

**Issue by simonelanucara** [SP7-Ritmare/starterkit#132]
Trying to delete a layer from the admin interface the layer is not deleted, but an error appears: NoReverseMatch at /admin/layers/layer/
screenshot attached
![remove_layer_error](https://user-images.githubusercontent.com/7208995/40912011-ac58893e-67f0-11e8-913c-8e68046be30e.jpg)

**Comment by wlorenzetti** [comment]
Fixed with #133 pul request just merged.

**Comment by simonelanucara** [comment]
The issue is still present, tried on two different installation of get-it (one fresh install) on two infrastructures.
screehshot attached
![immagine](https://user-images.githubusercontent.com/7208995/42408756-1b9e8150-81d1-11e8-9900-fc17be485934.jpg)
